= LANV, lacanvas, LADI Canvas

.WORK IN PROGRESS
[NOTE]
This is Work In Progress for adapting
https://drobilla.net/software/flowcanvas.html[flowcanvas] plus
https://ladish.org/[gladish] augmentations into new C library
along with adding new features, like port grouping.
Beware that in this WIP version of the text,
present tense may be used for not yet implemented things.

https://ladish.org/lanv.html[LANV] is project for providing canvas
helper libraries with level of API abstraction provided higher than
that of https://wiki.gnome.org/Projects/GooCanvas[GooCanvas] and
https://www.freshports.org/graphics/libgnomecanvas/[gnomecanvas]
by providing domain specific semantics.
In case of lanv, domain specific semantics is about
representing DSP flows.
Features from the https://drobilla.net/software/ganv.html[Ganv] library,
the flowcanvas successor, are also adopted.

Uses for such library include visual representation of
graphs provided in software modules like:

 * https://jackaudio.org/[JACK Audio Connection Kit graph representation]
 * graph of https://lv2plug.in/[LV2 plugins]
 * graph of kernel-mode DSP modules
 * graph of FPGA rendered DSP modules

Features:

 * Minimal dependencies, plain C implementation.
   In particular, C\++ runtime library is to be pulled as dependency only
   if C++ bindings are actually used.
 * flowcanvas/gladish-canvas/ganv/HoustonPatchbay-like domain level API
 * Libraries that target diverse set of raster UI environments:
  - X11, especially via libxcb
  - libnsfb
  - linux framebuffer
  - sixel over tty
  - Hardware accelerated 2D rendering via:
    . OpenVG
  - Hardware accelerated 3D rendering via:
    . OpenGL and GLX
    . OpenGL ES and EGL
  - Widgets for diverse set of GUI toolkits:
    . GNOME2/GTK2
    . GNOME3/GTK3
    . GNOME40/GTK4
    . KDE/Qt
 * Usable over range of lower level canvas layers, e.g.:
  - GooCanvas (liblacan-goo-gtk3)
  - GnomeCanvas2, flowcanvas style (liblacan-gnomecanvas-gtk2)
  - Cairo, ganv style, but without GTK requirement. (liblacan-cairo)
 * Port grouping (along with group-connect and group-disconnect)
 * Native Language Support (via gettext)
 * Colour theme support, including system-wide theme and custom themes.
 * Runtime customizable canvas background (liblanv-kilim)
   via wallpaper-like raster or vector images in scaled or pattern mode.
 * Photo-realistic renderings (liblanv-photo):
  - rack-mountable (liblanv-rack)
  - stage-floor (liblanv-floor)
 * Higher level language bindings for:
  - Python
  - Lua
  - C#
  - C++
  - Rust
  - Vala
