:keywords: LADI, canvas, LANV, lacanvas, flowcanvas, Ganv, HoustonPatchbay, GooCanvas, Cairographics

= LANV, lacanvas, LADI Canvas

.WORK IN PROGRESS
[NOTE]
This is Work In Progress for adapting
https://drobilla.net/software/flowcanvas.html[flowcanvas] plus
https://ladish.org/[gladish] augmentations into new C library
along with adding new features, like port grouping.
Beware that in this WIP version of the text,
present tense may be used for not yet implemented things.

https://ladish.org/lanv.html[LANV] is project to provide set of
libraries useful when creating visual representation of graphs on
raster display.

Canvas drawing of modular DSP/Audio/MIDI flow and
finite-state machine graphs like:

 * https://jackaudio.org/[JACK Audio Connection Kit] graphs
 * graphs of https://lv2plug.in/[LV2 plugins]
 * graphs of DSP modules in kernel-mode
 * graphs of DSP modules in FPGA

API with domain specific semantics at level similar to
https://drobilla.net/software/flowcanvas.html[flowcanvas],
https://drobilla.net/software/ganv.html[Ganv] and
https://github.com/Houston4444/HoustonPatchbay[HoustonPatchbay].

Operates on top of lower level canvas library like
https://wiki.gnome.org/Projects/GooCanvas[GooCanvas],
https://www.freshports.org/graphics/libgnomecanvas/[gnomecanvas]
or https://www.cairographics.org/[Cairo].

Features:

 * Minimal dependencies, plain C implementation.
   In particular, C\++ runtime library is to be pulled as dependency only
   if C++ bindings are actually used.
 * flowcanvas/gladish-canvas/ganv/HoustonPatchbay-like domain level API
 * Libraries that target diverse set of raster UI environments:
  - X11, especially via libxcb
  - libnsfb
  - linux framebuffer
  - sixel over tty
  - Hardware accelerated 2D rendering via:
    . OpenVG
  - Hardware accelerated 3D rendering via:
    . OpenGL and GLX
    . OpenGL ES and EGL
  - Widgets for diverse set of GUI toolkits:
    . GNOME2/GTK2 (liblanv-gtk2)
    . GNOME3/GTK3 (liblanv-gtk3)
    . GNOME40/GTK4
    . KDE/Qt
 * Usable over range of lower level canvas layers, e.g.:
  - GooCanvas (liblacanvas-goo-gtk3)
  - GnomeCanvas2, flowcanvas style (liblacanvas-gnome2)
  - Cairo, ganv style, but without GTK requirement. (liblacanvas-cairo)
 * Port grouping (along with group-connect and group-disconnect)
 * Native Language Support (via gettext)
 * Colour theme support, including system-wide theme and custom themes.
 * Runtime customizable canvas background (liblanv-kilim)
   via wallpaper-like raster or vector images in scaled or pattern mode.
 * Photo-realistic renderings (liblanv-photo):
  - rack-mountable (liblanv-rack)
  - stage-floor (liblanv-floor)
 * Language bindings:
  - Python
  - Lua
  - C#
  - C++
  - Rust
  - Vala
